### ISSUE TITLE
Orderbook and Candles in Context. C#

### ISSUE THREAD

**Issue by Pavel-Ter-Mikaelyan** [TinkoffCreditSystems/invest-openapi-csharp-sdk#14]
Добрый день. Подскажите пожалуйста, не нашел методов для получения истории по стакану и свечам в классе Context пространства Tinkoff.Trading.OpenApi.Network. В пространстве Tinkoff.Trading.OpenApi.Models есть классы CandlePayload, CandleInterval, OrderbookPayload, OrderbookResponse, но как эти объекты получить для необходимого инструмента, зная его FIGI или Ticker?

**Comment by 0pd** [comment]
Здравствуйте.
Это свежая функциональность, следите за issues #9 и #10, на этой неделе сделаем.
Перечисленные вами модели используются в streaming-протоколе.
