### ISSUE TITLE
[RequestNewFeature] Current sell and buy prices in MarketInstrument object

### ISSUE THREAD

**Issue by Ace-Lightning** [TinkoffCreditSystems/invest-openapi-csharp-sdk#17]
Hi,

Is it possible to add last sell and buy prices in `MarketInstrument` object and add method `Refresh` to update them?

**Comment by 0pd** [comment]
Hi, Sergey.

This SDK gives the ability to get those prices by the following options:

- `Context.OrderbookAsync` called with `depth = 1` will return it once
- A subscription made of `OrderbookSubscribeRequest` will raise `Context.StreamingEventReceived` event on every data update

You can use one of these ways to obtain the prices or even to create an abstraction over the `MarketInstrument` class. 

The SDK itself doesn't aim to implement all user stories but to provide basic support of the API.
