### ISSUE TITLE
[Bug] MarketSearchByFigiAsync doesn't work

### ISSUE THREAD

**Issue by Ace-Lightning** [TinkoffCreditSystems/invest-openapi-csharp-sdk#18]
Hi,

Function `MarketSearchByFigiAsync` doesn't work. When I try to get instrument by its Figi, it doesn't exist. Maybe I don't get something.

Repro steps for the issue:
```csharp
var instruments = await connection.Context.MarketSearchByTickerAsync("MSFT");
var instrumentsByFigi = await connection.Context.MarketSearchByFigiAsync(instruments.Instruments[0].Figi);
```
**Expected:**
`instruments` contains one instrument, `instrumentsByFigi` contains the same instrument as in `instruments`

**Actual:**
`instruments` contains one instrument, `instrumentsByFigi` doesn't contain any

**Comment by visualserg** [comment]
When call method /market/search/by-ticker
Response with array 'instruments'
{
  "trackingId": "string",
  "status": "string",
  "payload": {
    "total": 0,
    "instruments": [
      {
        "figi": "string",
        "ticker": "string",
        "isin": "string",
        "minPriceIncrement": 0,
        "lot": 0,
        "currency": "RUB",
        "name": "string",
        "type": "Stock"
      }
    ]
  }
}

When call method /market/search/by-figi
Response without array 'instruments'
{
  "trackingId": "string",
  "status": "string",
  "payload": {
    "figi": "string",
    "ticker": "string",
    "isin": "string",
    "minPriceIncrement": 0,
    "lot": 0,
    "currency": "RUB",
    "name": "string",
    "type": "Stock"
  }
}

In test https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/master/tests/Tinkoff.Trading.OpenApi.Tests/ContextTests.cs
check with array instruments
