### ISSUE TITLE
IContext.PortfolioAsync don't provide brokerAccountId

### ISSUE THREAD

**Issue by beholderrk** [TinkoffCreditSystems/invest-openapi-csharp-sdk#24]
### Ru

Добрый день. Метод `IContext.PortfolioAsync` похоже отсырел, т.е. не принимает `brokerAccountId`. В [swagger](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio) этот параметр есть.

Кстати, откуда `brokerAccountId` можно взять?

### En

Hi. The `IContext.PortfolioAsync` method looks very old, i.e. don't accepts `brokerAccountId`. In [swagger](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio) this parameter is.

By the way, where can I get `brokerAccountId`?

**Comment by NikitaMelnikov** [comment]
Добрый день,

brokerAccountId доступен в методе /user/accounts https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/user/get_user_accounts

**Comment by NikitaMelnikov** [comment]
Если не передавать параметр brokerAccountId, то по-умолчанию будет использоваться брокерский счет

**Comment by rus-art** [comment]
Пофиксили в 1.3.0
