### ISSUE TITLE
GATEWAY_REQUEST_DATA_ERROR: Unknown account(....)

### ISSUE THREAD

**Issue by GennadyPrasolov** [TinkoffCreditSystems/invest-openapi-csharp-sdk#25]
При попытке получить портфель из песочницы следующим образом:

```
 var connection = ConnectionFactory.GetSandboxConnection(sandboxToken);
 var context = connection.Context;
var portfolio = await context.PortfolioAsync();

```
Вываливается исключение  GATEWAY_REQUEST_DATA_ERROR: Unknown account(....). Так и должно быть? С продакшеном все ок.

**Comment by NikitaMelnikov** [comment]
Нужно вызвать метод регистрации в сендбоксе

**Comment by turanda** [comment]
> Нужно вызвать метод регистрации в сендбоксе

Как его вызвать? можно пример для C#

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/master/src/Tinkoff.Trading.OpenApi/Network/SandboxContext.cs#L14
