### ISSUE TITLE
Sdk C# _ START

### ISSUE THREAD

**Issue by Ale5887** [TinkoffCreditSystems/invest-openapi-csharp-sdk#26]
Добрый день! Помогите пл..
    using Tinkoff.Trading.OpenApi.Network;
    ...
    // токен аутентификации
    var token = "my.token";
    // для работы в песочнице используйте GetSandboxConnection
    var connection = ConnectionFactory.GetConnection(token);
    var context = connection.Context;

    // вся работа происходит асинхронно через объект контекста
    var portfolio = await context.PortfolioAsync();

    Правильно ли  понял: переменной token присваиваю свой тукен 
    а всё остальное уже прописано в sdk (url,wc и т.д) 

    portfolio  надо распарсивать ????  Возвращается в формате Json ???

    Не могу понять как вывести для просмотра ...
    Можно пример для С# 
    C nodejs  разобрался, а вот в C# никак ..

    За ранее спасибо.

**Comment by Ale5887** [comment]
С этим разобрался, теперь не могу понять как подписаться на свечу и стакан..
Вижу что есть public class CandlePayload
    {
        public decimal Open { get; }
        public decimal Close { get; }
        public decimal High { get; }
        public decimal Low { get; }
        public decimal Volume { get; }
        public DateTime Time { get; }
        public CandleInterval Interval { get; }
        public string Figi { get; }
 как не могу понять

**Comment by rus-art** [comment]
Пример [выложил](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/tree/master/samples/TradingBot)
Если есть еще вопросы по примеру, предлагаю переместить обсуждение в #19

**Comment by rus-art** [comment]
Duplicate of #19
