### ISSUE TITLE
PlaceLimitOrderAsync

### ISSUE THREAD

**Issue by d-kochanzhi** [TinkoffCreditSystems/invest-openapi-csharp-sdk#27]
Добрый день,

устанавливаю в песочнице себе баланс (все по 99 уе):

await context.SetCurrencyBalanceAsync(Tinkoff.Trading.OpenApi.Models.Currency.Rub, 99);
await context.SetCurrencyBalanceAsync(Tinkoff.Trading.OpenApi.Models.Currency.Usd, 99);
await context.SetPositionBalanceAsync("BBG0013HGFT4", 99);

но при попытке поставить заявку на покупку пишет НЕТ денег

PlacedLimitOrder placedLimitOrder =  await context.PlaceLimitOrderAsync(new LimitOrder("BBG0013HGFT4", 1, OperationType.Buy, 1));

NOT_ENOUGH_BALANCE: Cannot process request, not enough balance on security=RUB (da9daa52f8eb6dd1).

Можете сказать в чем дело?

**Comment by d-kochanzhi** [comment]
@NikitaMelnikov можете ответить?

**Comment by NikitaMelnikov** [comment]
Прошу прощения, потерялось уведомление
Сейчас воспроизводится?

**Comment by rus-art** [comment]
Увеличьте стартовый баланс хотя бы до 1000. Я проверил, так работает.
