### ISSUE TITLE
Handle closed web socket connections

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi-csharp-sdk#28]
When a web socket connection is closed, the library doesn't notify a client about the event.
Therefore, it's very hard to implement a reconnection logic in apps.

Steps to reproduce:

1. Subscribe to any event using `SendStreamingRequestAsync`
2. Close the created WS connection using TcpView (you can use any other tool for this)

Expected result:
The library throws an exception or sends an event to a client or tries automatically reconnect to the server

Actual result:
The library does nothing

**Comment by RWander** [comment]
Is there any workaround to fix it?

**Comment by RWander** [comment]
I have faced with this problem too. After 2 hours, the connection to the websocket is lost without any error/notifiactoin.

**Comment by olsh** [comment]
@RWander 
There is a workaround which kind of works.
I set up a custom [Timer](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer?view=netframework-4.8) which reconnects if there were no streaming events for one minute.

**Comment by RWander** [comment]
@olsh,
Ok, thanks for the quick reply! It would be great if you shared your workaround.

**Comment by rus-art** [comment]
@olsh, посмотри, пожалуйста, #49. Покрывает ли оно этот кейс?

**Comment by olsh** [comment]
@rus-art да, отрабатывает, спасибо! 👍 
При закрытии соединения прилетает событие `WebSocketException`
