### ISSUE TITLE
Improve JSON deserialization exception handling

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi-csharp-sdk#32]
Sometimes the REST API server returns something, but not a JSON.
In this cases the deserialization fails here:
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/286a44a9c6fa1e0a2030f1334df3b08226e01d09/src/Tinkoff.Trading.OpenApi/Network/Connection.cs#L71-L86

And in your stack traces you get an unclear error, something like that:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
  Module "Newtonsoft.Json.JsonTextReader", in ParseValue
  Module "Newtonsoft.Json.JsonReader", in ReadForType
  Module "Newtonsoft.Json.Serialization.JsonSerializerInternalReader", in Deserialize
  Module "Newtonsoft.Json.JsonSerializer", in DeserializeInternal
  Module "Newtonsoft.Json.JsonConvert", in DeserializeObject
  Module "Newtonsoft.Json.JsonConvert", in DeserializeObject
  Module "Tinkoff.Trading.OpenApi.Network.Connection`1+<HandleResponseAsync>d__14`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "Tinkoff.Trading.OpenApi.Network.Connection`1+<SendGetRequestAsync>d__11`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "Tinkoff.Trading.OpenApi.Network.Context", in OrdersAsync
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
```

It would be nice to see the real error or raw response, at least.

**Comment by olsh** [comment]
@NikitaMelnikov 
Я бы взялся это улучшить и другие возможно тоже, но тотальное игнорирование существующих PRs (https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/31 https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/21) отбивает все желание посылать новые.

**Comment by NikitaMelnikov** [comment]
Добрый день,

Я понимаю ситуацию, полностью с вами согласен
В данный момент мы занимаемся поиском мейнтейнера на проект, ограничение накладывает то, что этим мейнтейнером должен выступать сотрудник компании.
Если в ближайшее время не получится определится, то будем отдавать проект в OS
