### ISSUE TITLE
Tinkoff.Trading.OpenApi.Network.OpenApiException: 'MALFORMED_QUERY_PARAMETER: Неверный формат поля 'from' в запросе (a8cb2d513d2ab297).'

### ISSUE THREAD

**Issue by ssolarevIDBS** [TinkoffCreditSystems/invest-openapi-csharp-sdk#39]
Tinkoff.Trading.OpenApi.Network.OpenApiException: 'MALFORMED_QUERY_PARAMETER: Неверный формат поля 'from' в за CandleList.
candleResult = await context.MarketCandlesAsync(r.Instruments[0].Figi, from, new DateTime(2019, 12, 31,0,0,0,DateTimeKind.Local), CandleInterval.Day);
            просе (a8cb2d513d2ab297).'

**Comment by ssolarevIDBS** [comment]
candleResult = await context.MarketCandlesAsync(r.Instruments[0].Figi, new DateTime(2019, 12, 31,0,0,0,DateTimeKind.Local, new DateTime(2019, 12, 31,0,0,0,DateTimeKind.Local), CandleInterval.Day);
просе (a8cb2d513d2ab297).'.


Сервер не воспринимает параметр FROM ни в каком варианте. Пишет - неверный формат. Что не так????

**Comment by ssolarevIDBS** [comment]
Ага нашел причину. Коллеги, в функции MarketCandlesAsync вы используете метод DateTime.ToString("o"), что не правильно. Она выдает дату в формате: "2020-05-01T17:04:32.0000000", а сервер ожидает дату в формате UTC: "2020-05-01T17:04:32.000Z". 
К сожалению в c# нет встроенного метода для данного преобразования, поэтому нужно обрезать последние 4 цифры и добавить Z.

**Comment by RWander** [comment]
Похоже проблема в том, что даты во всех response приходят с Kind=Unspecified. 
Если API возвращает даты в формате UTC, то нужно, чтобы свойство date.Kind ,было равно DateTimeKind.Utc. Тогда DateTime.ToString("o") вернет дату в формате UTC.

**Comment by rus-art** [comment]
> candleResult = await context.MarketCandlesAsync(r.Instruments[0].Figi, new DateTime(2019, 12, 31,0,0,0,DateTimeKind.Local, new DateTime(2019, 12, 31,0,0,0,DateTimeKind.Local), CandleInterval.Day);
> просе (a8cb2d513d2ab297).'.
> 
> Сервер не воспринимает параметр FROM ни в каком варианте. Пишет - неверный формат. Что не так????

Конкретно этот код выдает ошибку "Bad candle interval". Перенес from на немного пораньше и запрос отработал без ошибок.
```
                await context.MarketCandlesAsync("BBG000CL9VN6",
                new DateTime(2019, 12, 28, 0, 0, 0, DateTimeKind.Local),
                new DateTime(2019, 12, 31, 0, 0, 0, DateTimeKind.Local), CandleInterval.Day);
```

Подскажите, что конкретно было в from? Видимо дата с DateTimeKind.Unknown, попробовал - ошибка один в один.

Так как уже много было вопросов на эту тему, я предлагаю автоматически приводить все даты с DateTimeKind Unknown в Local

**Comment by rus-art** [comment]
> Похоже проблема в том, что даты во всех response приходят с Kind=Unspecified.
> Если API возвращает даты в формате UTC, то нужно, чтобы свойство date.Kind ,было равно DateTimeKind.Utc. Тогда DateTime.ToString("o") вернет дату в формате UTC.

Проверил, API возвращает UTC
