### ISSUE TITLE
Program just stops executing on context.PortfolioAsync() without errors

### ISSUE THREAD

**Issue by penoplaster83** [TinkoffCreditSystems/invest-openapi-csharp-sdk#44]
using Tinkoff.Trading.OpenApi.Network;
...
// токен аутентификации
var token = "мой супер токен";

var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;

// вся работа происходит асинхронно через объект контекста
**var portfolio = await context.PortfolioAsync();**

**Инструкции расположенные ниже по коду не выполняются. Программа именно вылетает. Ошибок не выплёвывает. В чем дело, подскажите плиз**

**Comment by penoplaster83** [comment]
@NikitaMelnikov Можно ли выложить простой пример рабочего приложения?

**Comment by NikitaMelnikov** [comment]
@rus-art

**Comment by rus-art** [comment]
Вопрос так же в примере, переместимся в другой issue

Duplicate of #19

**Comment by rus-art** [comment]
Duplicate of #19
