### ISSUE TITLE
Запуск простейшего примера на C#. GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes.

### ISSUE THREAD

**Issue by Casper-SC** [TinkoffCreditSystems/invest-openapi-csharp-sdk#47]
Здравствуйте. Изначально была ошибка такая. Пусть будет здесь решение, пригодится кому-нибудь. Всё сделал по инструкции, запускаю приложение и вижу ошибку: 

> Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes (c8de689d4a5e2b60).
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
>    at Tinkoff.Trading.OpenApi.Network.Context.AccountsAsync()
>    at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 31

Удалил из токена в начале "t.". Про то, что это нужно сделать нигде не написано.

Код:
```
using System;
using System.Threading.Tasks;
using Tinkoff.Trading.OpenApi.Network;

namespace TinkoffTradingRobot
{
    class Program
    {
        private static Program _program;

        private static Task Main(string[] args)
        {
            _program = new Program();
            return _program.Run(args);
        }

        private async Task Run(string[] args)
        {
            // токен аутентификации
            string token = "Токен сгенерировал по инстукции. Это Sandbox.";

            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetConnection(token);
            using var context = connection.Context;
            try
            {
                // вся работа происходит асинхронно через объект контекста
                var portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadKey();
        }
    }
}
```

**Comment by rus-art** [comment]
В коде происходит работа с песочницей, значит нужно использовать токен для песочницы.
`t.` удалять не надо.
![image](https://user-images.githubusercontent.com/18074929/84503008-0ffb9400-acc2-11ea-9258-b6fb41524d1e.png)

**Comment by rus-art** [comment]
Извиняюсь, неверно прочитал. Если хотите работать с песочницей, используйте метод GetSandboxConnection
```var connection = ConnectionFactory.GetSandboxConnection(token);```

**Comment by Casper-SC** [comment]
Сгенерировал новый токен. Всё равно пишет ошибку. Это точно Sandbox:
```
Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Unknown account (fd05cbe47e783330).
   at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
   at Tinkoff.Trading.OpenApi.Network.Context.PortfolioAsync(String brokerAccountId)
   at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 33
```

Код:
```
        private async Task Run(string[] args)
        {
            // токен аутентификации
            string token = "t.8Q";

            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetSandboxConnection(token);
            using var context = connection.Context;
            try
            {
                // вся работа происходит асинхронно через объект контекста
                var portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadKey();
        }
    }
```

**Comment by rus-art** [comment]
Он не может найти аккаунт, так как в песочнице их нет
Сначала надо его создать
``` _context.RegisterAsync(BrokerAccountType.Tinkoff);```
Я работаю над примером

**Comment by rus-art** [comment]
Пример [выложил](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/tree/master/samples/TradingBot)
Если есть вопросы по примеру, давайте обсудим их в #19

**Comment by rus-art** [comment]
Duplicate of #19
