### ISSUE TITLE
Ошибка Access Denied: You have no access to that resource

### ISSUE THREAD

**Issue by Casper-SC** [TinkoffCreditSystems/invest-openapi-csharp-sdk#48]
Продолжение темы [Запуск простейшего примера на C#. GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/issues/47).

> Tinkoff.Trading.OpenApi.Network.OpenApiException: Access Denied: You have no access to that resource..
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
>    at Tinkoff.Trading.OpenApi.Network.Context.PortfolioAsync(String brokerAccountId)
>    at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 33

Код:
```
using System;
using System.Threading.Tasks;
using Tinkoff.Trading.OpenApi.Network;

namespace TinkoffTradingRobot
{
    class Program
    {
        private static Program _program;

        private static Task Main(string[] args)
        {
            _program = new Program();
            return _program.Run(args);
        }

        private async Task Run(string[] args)
        {
            // токен аутентификации
            string token = "Токен сгенерировал по инстукции. Это Sandbox.";

            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetConnection(token);
            using var context = connection.Context;
            try
            {
                // вся работа происходит асинхронно через объект контекста
                var portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            Console.ReadKey();
        }
    }
}
```

**Comment by rus-art** [comment]
Токен без `t.` вначале невалиден, поэтому возникла эта ошибка

**Comment by Casper-SC** [comment]
Вот я невнимательный, там же прямо в комментарии написано. 

Изменил, как вы написали
```
        private async Task Run(string[] args)
        {
            // токен аутентификации
            string token = "t._wyUw-токен от Песочницы";

            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetSandboxConnection(token);
            using var context = connection.Context;
            try
            {

                //var accounts = await context.AccountsAsync();
                // вся работа происходит асинхронно через объект контекста
                var portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
```

Выдаёт ошибку: 

> Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Unknown account (1ae2723becc7922d).
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
>    at Tinkoff.Trading.OpenApi.Network.Context.PortfolioAsync(String brokerAccountId)
>    at TinkoffTradingRobot.Program.Run(String[] args) in F:\Programming\C#\WORK\TinkoffTradingRobot\TinkoffTradingRobot\Program.cs:line 34
