### ISSUE TITLE
Невозможно получить операции по инструменту, которого нет в портфеле

### ISSUE THREAD

**Issue by VitalyTartynov** [TinkoffCreditSystems/invest-openapi-csharp-sdk#53]
Хочу получить операции по инструменту, который был ранее в портфеле и был продан, но получаю пустой список операций. Есть ли возможность получить такую историю?
https://gist.github.com/VitalyTartynov/ea5f3ac341fd288dca6d464698e7c2a2

**Comment by rus-art** [comment]
@NikitaMelnikov призываю тебя)

**Comment by VitalyTartynov** [comment]
Небольшое, но, возможно, критичное уточнение. YNDX был "подарком" после регистрации.

**Comment by VitalyTartynov** [comment]
Issue можно закрывать, история операций по "реальному" инструменту, который был продан получается. Видимо, дело реально в том, что "подаренные" инструменты обрабатываются иначе и операций по ним реально нет.

**Comment by NikitaMelnikov** [comment]
@VitalyTartynov все верно, подарки это отдельный продукт, в OpenApi его нет
