### ISSUE TITLE
PlaceLimitOrderAsync: необходимо возвращать причину отклонения заявки в случае Rejected.

### ISSUE THREAD

**Issue by RWander** [TinkoffCreditSystems/invest-openapi-csharp-sdk#58]
Response запроса PlaceLimitOrderAsync в случае Status=Rejected имеет RejectedStatus=Unknown. В то время как https://www.tinkoff.ru/invest-terminal при размещение той же заявки выдает истинную причину ошибки:

![image](https://user-images.githubusercontent.com/2590778/93073765-782c8e00-f694-11ea-85fe-ca4e2cf4f4e9.png)

**Comment by rus-art** [comment]
Уже заведен [запрос ](https://github.com/TinkoffCreditSystems/invest-openapi/issues/89) на улучшение в репозитории с API
