### ISSUE TITLE
Не исполняется рыночная заявка PlaceMarketOrderAsync:  RejectedReason = Unknown

### ISSUE THREAD

**Issue by victordoshenko** [TinkoffCreditSystems/invest-openapi-csharp-sdk#61]
В момент совершения рыночной заявки система возвращает response.RejectReason = 'Unknown'. Как понять почему не исполнилась заявка?
```
        public async void DoMarketOrder(OperationType operationType)
        {
            var response = await _context.PlaceMarketOrderAsync(new MarketOrder(figi, int.Parse(tbLots.Text), operationType, _accountId));
            WriteLog(operationType.ToString() + " " + tbLots.Text + " " + cbInstrument.Text + " " + response.Status.ToString() + " " + response.RejectReason);
        }
```
![image](https://user-images.githubusercontent.com/19908367/93389575-03647a00-f875-11ea-8ab3-37af3d511aae.png)
Могло ли повлиять то, что заявку выставлял после 23:00?

**Comment by RWander** [comment]
There is the similar problem with PlaceLimitOrderAsync: #58.

**Comment by victordoshenko** [comment]
Сегодня с утра проверил, работает, рыночные ордера на продажу и покупку выставляются нормально. Но по причине отказа вопрос в силе. Нужна детализация причины отказа.

**Comment by Dazlonar** [comment]
Вчера писал в сапорт по той же проблеме, ответили что на спб бирже рыночные заявки недоступны после 23 часов

**Comment by rus-art** [comment]
Уже заведен [запрос ](https://github.com/TinkoffCreditSystems/invest-openapi/issues/89) на улучшение в репозитории с API
