### ISSUE TITLE
Заменить Newtonsoft.Json на System.Text.Json

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi-csharp-sdk#65]
Было бы неплохо мигрировать с [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) на [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/)

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

- Newtonsoft.Json перешел в maintenance mode и не будет активно развиваться. В то время как System.Text.Json активно развивается и поддерживается MicroSoft
- System.Text.Json быстре чем Newtonsoft.Json ([производительность стала еще лучше в .NET 5.0](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/#json))
- Начиная с .NET Core 3.1 System.Text.Json входит в стандартные зависимости

**Comment by RWander** [comment]
+1
Давно пора перейти на System.Text.Json.

**Comment by olsh** [comment]
Реализовал пробный вариант с `System.Text.Json`
Скорость в ~4 раза быстрее, выделение памяти в ~8 раз меньше.

|         Method |      Mean |     Error |    StdDev | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |----------:|----------:|----------:|------:|-------:|------:|------:|----------:|
| NewtonsoftJson | 36.728 us | 0.3493 us | 0.3267 us |  1.00 | 5.1270 |     - |     - |  15.88 KB |
| SystemTextJson |  9.706 us | 0.1114 us | 0.0988 us |  0.26 | 0.6104 |     - |     - |   1.88 KB |

Тестировал в .NET Core 3.1, код тестирования:
```csharp
    [MemoryDiagnoser]
    public class StringReplaceVsStringBuilder
    {
        string _json;

        [GlobalSetup]
        public void Setup()
        {
            _json = @"{
  ""event"": ""candle"",
  ""time"": ""2019-08-07T15:35:01.029721253Z"",
  ""payload"": {
    ""o"": 64.0575,
    ""c"": 64.0578,
    ""h"": 64.0579,
    ""l"": 64.0573,
    ""v"": 156,
    ""time"": ""2019-08-07T15:35:00Z"",
    ""interval"": ""5min"",
    ""figi"": ""BBG0013HGFT4""
  }
}
";
        }

        [Benchmark(Baseline = true)]
        public Old.StreamingResponse NewtonsoftJson()
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Old.StreamingResponse>(_json);
        }

        [Benchmark]
        public New.StreamingResponse SystemTextJson()
        {
            return System.Text.Json.JsonSerializer.Deserialize<New.StreamingResponse>(_json);
        }
    }
```

**Comment by ILAgent** [comment]
Почему не мёржится pr?
