### ISSUE TITLE
Невозможно подписаться на события получения стакана или свечей более чем на одну бумагу в одном соединении

### ISSUE THREAD

**Issue by t1mur619533** [TinkoffCreditSystems/invest-openapi-csharp-sdk#68]
Добрый день! Обнаружил, что при подписке на события получения стакана или свечей по веб сокетам невозможно получить данные по нескольким бумагам, только одна бумага на один Context. При подписке на еще на какие то бумаги (через метод SendStreamingRequestAsync) - приходит информация только по первой, остальные игнорируются. Не нашел нигде в документации описания о таких ограничениях. Это бага или все же фича? ) Спасибо!

**Comment by dlinnozmey** [comment]
Await при подписке на стакан/свечи/etc спасёт отца трейдинга😁
