### ISSUE TITLE
получение элемента графика сайта

### ISSUE THREAD

**Issue by SergeyToff** [TinkoffCreditSystems/invest-openapi-csharp-sdk#73]
есть ли какой-то запрос, который получает идентичную картину сайту? 
В свечах абсолютно другие значения, а хотелось бы сравнивать стратегию с сайтом.
Скорее всего я просто не понимаю, как формируется цена из Open Close High Low, но все же, буду рад ответу))

скрин прилагаю
![image](https://user-images.githubusercontent.com/14993797/108635386-3b10c700-7490-11eb-8209-13aa9f8e8349.png)

**Comment by SergeyToff** [comment]
время в utc, нужно -3

**Comment by rus-art** [comment]
#70
