### ISSUE TITLE
Подскажите, как правильно пересоздавать сокет?

### ISSUE THREAD

**Issue by OdCheban** [TinkoffCreditSystems/invest-openapi-csharp-sdk#74]
Проблема в том, что 1-2 раза в день WebSocketException возвращает ошибку из-за которой сокет переходит в состояние "Aborted", после чего было бы логично:  
переподписаться на получение свечей и методы т.е. SendStreamingRequestAsync(StreamingRequest.UnsubscribeCandle()), и после StreamingRequest.SubscribeCandle() - но получаю ошибку "с# The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'"
Корректно ли в этом случае просто создать новое подключение таким образом ConnectionFactory.GetConnection(Token.work).Context?

**Comment by rus-art** [comment]
Да, можете так сделать. Библиотека пока не обрабатывает такую ошибку, если есть желание - можете дописать обработку.
