### ISSUE TITLE
Ошибка при десериализации InstrumentInfoPayload

### ISSUE THREAD

**Issue by t3chn0pr13st** [TinkoffCreditSystems/invest-openapi-csharp-sdk#75]
Для инструмента BBG000RG4ZQ4 при десериализации InstrumentInfoPayload возникает исключение 
System.Text.Json.JsonException: 'The JSON value could not be converted to Tinkoff.Trading.OpenApi.Models.InstrumentInfoPayload. Path: $.lot | LineNumber: 0 | BytePositionInLine: 94.'
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.

При этом сам payload содержит
{"figi":"BBG000RG4ZQ4","trade_status":"normal_trading","min_price_increment":1e-05,"lot":1e+06}

![image](https://user-images.githubusercontent.com/24903894/108977374-877b2300-7699-11eb-9f1e-f08c33606a32.png)

**Comment by t3chn0pr13st** [comment]
Для себя форкнул и поменял тип поля Lot c int на decimal, ошибка ушла. Если такой вариант решения подходит, могу пулл реквест сделать)

**Comment by RWander** [comment]
Да, лучше сделай пул реквест

**Comment by rus-art** [comment]
По [спецификации](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/) там int
> lot*  integer($int32)
Лучше оставить int. Это можно пофиксить, если указать NumberStyles при парсинге
`int.Parse("1e+06", NumberStyles.Float)` дает 1000000

**Comment by rus-art** [comment]
@t3chn0pr13st Посмотри PR, пожалуйста. Вроде удалось пофиксить

**Comment by t3chn0pr13st** [comment]
> @t3chn0pr13st Посмотри PR #79, пожалуйста. Вроде удалось пофиксить

Большое спасибо, влил себе этот коммит, теперь всё работает как надо.

**Comment by rus-art** [comment]
Хорошо, мержу
