### ISSUE TITLE
[!] Ошибка сериализации после перехода на 1.7.1

### ISSUE THREAD

**Issue by RWander** [TinkoffCreditSystems/invest-openapi-csharp-sdk#77]
После перехода на новую версию 1.7.1 с использованием System.Text.Json.JsonSerializer на .NET 5 перестала корректно работать серилизация (см скрин): свойства Figi и Interval отсутствуют в requestJson.

![image](https://user-images.githubusercontent.com/2590778/109464268-da7d1d80-7a7f-11eb-822c-7d24e14e387a.png)

**Comment by RWander** [comment]
Проблема описана [тут](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism). 

[PR 78](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/78)

**Comment by rus-art** [comment]
Спасибо за фикс
