### ISSUE TITLE
Не хватает CancellationToken в методе SendStreamingRequestAsync

### ISSUE THREAD

**Issue by danclax** [TinkoffCreditSystems/invest-openapi-csharp-sdk#80]
Когда нужно остановить сервис, через cancellation token удобно (и это best practice) мягко и корректно завершать все асинхронные операции

**Comment by danclax** [comment]
Вот пример изменения кода - https://github.com/danclax/invest-openapi-csharp-sdk/pull/1
Интерфейс не ломает, зато дает возможность отменить процесс подключения

**Comment by rus-art** [comment]
Спасибо! Вы могли бы создать PR [тут](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pulls)? Я что-то не вижу там ваш репозиторий в списке форков

**Comment by danclax** [comment]
Я как-то криво форканул. Сделал в новом репо и создал PR: https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/84

**Comment by rus-art** [comment]
Спасибо!
