### ISSUE TITLE
Информация по совершенным сделкам в реальности

### ISSUE THREAD

**Issue by nospoon27** [TinkoffCreditSystems/invest-openapi-csharp-sdk#83]
Могу ли получить по API информацию по совершенным сделкам в реальности? По сути мне нужен брокерский отчет со всеми пополнениями, покупками, продажами, ценами и комиссиями

**Comment by rus-art** [comment]
[Это](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations) не оно?
