### ISSUE TITLE
Расхождение кол-ва купленных инструментов в Operations и Trades

### ISSUE THREAD

**Issue by sinhider** [TinkoffCreditSystems/invest-openapi-csharp-sdk#85]
Получаю сделки по инструменту методом OperationsAsync()

В объекте Operation поле Quantity равно 4-м, в коллекции Trades этого же объекта Operation, значение Quantity равно 2-м. Кол-во объектов в коллекции Trades - 1. При этом Payment в Operation имеет корректное значение.

Скрины

https://prnt.sc/11qqnur
https://prnt.sc/11qqotk

Кол-во операций в этот день - 1 (проверил по терминалу). Судя по всему оперировать надо данными из коллекции Trades объекта Operation. 

Версия SDK 1.7.3

**Comment by AlexanderVolkovTCS** [comment]
quantity - количество запрошенных лотов, quantityExecuted - количество исполненных. Второе должно совпадать в трейдами.
