### ISSUE TITLE
Не правильный FIGI в операциях статистики

### ISSUE THREAD

**Issue by ssolarevIDBS** [TinkoffCreditSystems/invest-openapi-csharp-sdk#90]
OperationsAsync для операций с FIGI=BBG00QPYJ5H0(Ticker=TCSG,Name=TCS Group,Currency=RUB) 
ошибочно возвращает FIGI=BBG005DXJS36(Ticker=TCS,Name=TCS Group,Currency=USD)

**Comment by rus-art** [comment]
Duplicate of https://github.com/TinkoffCreditSystems/invest-openapi/issues/493
