### ISSUE TITLE
Получение уведомлений об операциях

### ISSUE THREAD

**Issue by Stephan-Kuznetsov** [TinkoffCreditSystems/invest-openapi-csharp-sdk#91]
Добрый день!
Подскажите, пожалуйста, есть ли возможность подписаться на изменение статуса заявок?
То есть, например, если заявка исполняется или отменяется, получать уведомление об этом в приложении.

**Comment by rus-art** [comment]
Пока есть возможность осуществлять [эти](https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/) подписки. Если там нет того, что вам нужно, предлагаю завести issue с предложением в https://github.com/TinkoffCreditSystems/invest-openapi, или проверить, возможно там уже есть такое.
