### ISSUE TITLE
Дорбавить функционал для выбора портфеля (брокерского счета)

### ISSUE THREAD

**Issue by Voucik** [TinkoffCreditSystems/invest-openapi-csharp-sdk#93]
Добрый день. 
У меня несколько портфелей (счетов), в данный момент в апи доступен только один, это первый портфель.
Я нашел в скриптах сайта идентификаторы всех моих портфелей, попробовал их передать в параметре brokerAccountId:
![image](https://user-images.githubusercontent.com/6031632/126082658-fbc4b175-e74a-4383-a917-ae921bdcf5c4.png) 
Выяснилось, что работает только мой первый созданный счет, а в остальных случаях ругается:
![image](https://user-images.githubusercontent.com/6031632/126082715-99f9fd47-3dfd-4928-b3d0-2998fe99577b.png)
Просьба сделать выбор счетов или возможность сделать по умолчанию другой счет.

P.S.  И да, я в FAQ видел ответ по поводу мультисчетов и там говорится, что данный функционал в разработке, вот только это уже давно там висит, а конкретики нет, скажите хоть примерную дату.

**Comment by rus-art** [comment]
Это репозиторий исключительно с клиентом для доступа к api. Если не работает в api - у нас точно не будет работать. Да, вопрос уже обсуждается [тут](https://github.com/TinkoffCreditSystems/invest-openapi/issues/533), это и есть основное место для обсуждения
