### ISSUE TITLE
Отсутствует свойство quantityExecuted в классе Operation

### ISSUE THREAD

**Issue by NoviProg** [TinkoffCreditSystems/invest-openapi-csharp-sdk#95]
В классе Operation отсутствует свойство  quantityExecuted а в OpenAPI оно есть.
{
  "trackingId": "string",
  "status": "string",
  "payload": {
    "operations": [
      {
       ,,,
        "quantity": 0,
        "**quantityExecuted**": 0,
      ,,,
      }
P.S:
Скажите чем отличаются свойства  quantity и quantityExecuted?

**Comment by NoviProg** [comment]
P.S:
QuantityExecuted Nullable потому что в SandboxConnection оно никогда не возвращается.

**Comment by rus-art** [comment]
Спасибо.
quantity - Число инструментов в выставленной заявке
quantityExecuted - Число инструментов, исполненных в заявке
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/
