### ISSUE TITLE
Потенциальная ошибка приведения типов

### ISSUE THREAD

**Issue by NoviProg** [TinkoffCreditSystems/invest-openapi-csharp-sdk#97]
В файле https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/master/src/Tinkoff.Trading.OpenApi/SerializationOptions.cs в строке 28 (return (int) @decimal;) используется приведение вместо конвертации. Что может привести к потере данных при нормализации числа (если она не делается на стороне OpenAPI).

```
//Пример:

class JData
        {
            public int Quantity { get; }

            [JsonConstructor]
            public JData(int quantity)
            {
                Quantity = quantity;
            }
        }
        static void Main(string[] args)
        {

            var data = JsonSerializer.Deserialize("{\"Quantity\": 0.99999}", typeof(JData), SerializationOptions.Instance) as JData;
            Console.WriteLine($"Quantity: {data.Quantity}");
        }
// Output:
// Quantity: 0
```
Возможное решение:
Заменить 28 стр. 
`return (int) @decimal; `
на
`return Convert.ToInt32(@decimal);`
В этом случае будет возвращаться 
// Quantity: 1

P.S:

Возвращаемое значение
Int32
Значение value, округленное до ближайшего 32-разрядного целого числа со знаком. Если value имеет среднее значение между двумя целыми числами, будет возвращено четное число; так, значение 4,5 преобразуется в 4, а 5,5 — в 6.

https://docs.microsoft.com/ru-ru/dotnet/api/system.convert.toint32?view=net-5.0#System_Convert_ToInt32_System_Decimal_

**Comment by rus-art** [comment]
Спасибо за репорт. Нет, там не будет ошибки. Этот конвертер сделан, чтобы пофиксить #75, api для поля lot возвращает число в scientific представлении, хотя по спецификации имеем int. Везде, где по спецификации могут быть дробные значения, используется decimal. Например, `MarketInstrument.MinPriceIncrement`. И там, соответственно, этот конвертер не будет применяться.
