### ISSUE TITLE
Нельзя создать заявку (рыночную или лимитную) через ИИС.

### ISSUE THREAD

**Issue by OdCheban** [TinkoffCreditSystems/invest-openapi-csharp-sdk#98]
Не предусмотрена возможность вписать brokerAccountId в методы:
-Context.PlaceMarketOrderAsync(MarketOrder);
-Context.PlaceLimitOrderAsync(LimitOrder);

При этом методы Context.PortfolioAsync, .PortfolioCurrenciesAsync, OrdersAsyns и т.д. имеют в параметрах переменную "string brokerAccountId";
Как быть?

**Comment by AlexanderVolkovTCS** [comment]
К сожалению, существующая версия openAPI предполагает работу только с основным(первым) брокерским счетом и ИИС.
Мультисчета не поддерживаются, они будут в новой версии.

**Comment by OdCheban** [comment]
> К сожалению, существующая версия openAPI предполагает работу только с основным(первым) брокерским счетом и ИИС. Мультисчета не поддерживаются, они будут в новой версии.

речь не про мультисчета, а про ИИС

**Comment by AlexanderVolkovTCS** [comment]
@rus-art, можно добавить brokerAccountId в PlaceMarketOrderAsync/PlaceLimitOrderAsync?

**Comment by OdCheban** [comment]
@rus-art что в итоге? получится добавить?

**Comment by rus-art** [comment]
Посмотрите состав классов, пожалуйста, там есть broker account id
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/0fe472ec9d8e9108ca81bdde1907ddbd414d70cb/src/Tinkoff.Trading.OpenApi/Models/LimitOrder.cs#L11
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/0fe472ec9d8e9108ca81bdde1907ddbd414d70cb/src/Tinkoff.Trading.OpenApi/Models/MarketOrder.cs#L10
